const Map<String, String> teamNameToId = {
  'México': 'mex',
  'África do Sul': 'rsa',
  'Coréia do Sul': 'kor',
  'República Tcheca': 'cze',
  'Canadá': 'can',
  'Bósnia e Herzegovina': 'bih',
  'Catar': 'qat',
  'Suíça': 'sui',
  'Brasil': 'bra',
  'Marrocos': 'mar',
  'Haiti': 'hai',
  'Escócia': 'sco',
  'Estados Unidos': 'usa',
  'Paraguai': 'par',
  'Austrália': 'aus',
  'Turquia': 'tur',
  'Alemanha': 'ger',
  'Curaçao': 'cur',
  'Costa do Marfim': 'civ',
  'Equador': 'ecu',
  'Holanda': 'ned',
  'Japão': 'jpn',
  'Suécia': 'swe',
  'Tunísia': 'tun',
  'Bélgica': 'bel',
  'Egito': 'egy',
  'Irã': 'irn',
  'Nova Zelândia': 'nzl',
  'Espanha': 'esp',
  'Cabo Verde': 'cpv',
  'Arábia Saudita': 'ksa',
  'Uruguai': 'uru',
  'França': 'fra',
  'Senegal': 'sen',
  'Iraque': 'irq',
  'Noruega': 'nor',
  'Áustria': 'aut',
  'Jordânia': 'jor',
  'Argentina': 'arg',
  'Argélia': 'alg',
  'Portugal': 'por',
  'Congo': 'cod',
  'Uzbequistão': 'uzb',
  'Colômbia': 'col',
  'Inglaterra': 'eng',
  'Croácia': 'cro',
  'Gana': 'gha',
  'Panamá': 'pan',
};
